#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


liste = [1,2]
toplam = 0

while liste[-1] < 4000000:
    sayı = liste[-1] + liste[-2]
    liste.append(sayı)

for i in range(len(liste)):
    if liste[i] % 2 == 0:
        toplam += liste[i]

print(toplam)